// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="dot_product_dot_product,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.815750,HLS_SYN_LAT=5,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=475,HLS_SYN_LUT=563,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module dot_product (
        ap_clk,
        ap_rst_n,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 8;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [7:0] vec_a_0;
wire   [7:0] vec_a_1;
wire   [7:0] vec_a_2;
wire   [7:0] vec_a_3;
wire   [7:0] vec_a_4;
wire   [7:0] vec_a_5;
wire   [7:0] vec_a_6;
wire   [7:0] vec_a_7;
wire   [7:0] vec_b_0;
wire   [7:0] vec_b_1;
wire   [7:0] vec_b_2;
wire   [7:0] vec_b_3;
wire   [7:0] vec_b_4;
wire   [7:0] vec_b_5;
wire   [7:0] vec_b_6;
wire   [7:0] vec_b_7;
wire   [31:0] result;
reg    result_ap_vld;
reg    busy_ap_vld;
wire   [17:0] add_ln74_2_fu_329_p2;
reg   [17:0] add_ln74_2_reg_458;
wire    ap_CS_fsm_state5;
wire   [17:0] add_ln74_5_fu_355_p2;
reg   [17:0] add_ln74_5_reg_463;
wire   [15:0] grp_mac_unit_fu_213_ap_return;
wire   [15:0] grp_mac_unit_fu_221_ap_return;
wire   [15:0] grp_mac_unit_fu_229_ap_return;
wire   [15:0] grp_mac_unit_fu_237_ap_return;
wire   [15:0] grp_mac_unit_fu_245_ap_return;
wire   [15:0] grp_mac_unit_fu_253_ap_return;
wire   [15:0] grp_mac_unit_fu_261_ap_return;
wire   [15:0] grp_mac_unit_fu_269_ap_return;
wire    ap_CS_fsm_state6;
wire  signed [16:0] sext_ln58_fu_281_p1;
wire  signed [16:0] sext_ln57_fu_277_p1;
wire   [16:0] add_ln74_fu_309_p2;
wire  signed [16:0] sext_ln59_fu_285_p1;
wire  signed [16:0] sext_ln60_fu_289_p1;
wire   [16:0] add_ln74_1_fu_319_p2;
wire  signed [17:0] sext_ln74_1_fu_325_p1;
wire  signed [17:0] sext_ln74_fu_315_p1;
wire  signed [16:0] sext_ln61_fu_293_p1;
wire  signed [16:0] sext_ln62_fu_297_p1;
wire   [16:0] add_ln74_3_fu_335_p2;
wire  signed [16:0] sext_ln63_fu_301_p1;
wire  signed [16:0] sext_ln64_fu_305_p1;
wire   [16:0] add_ln74_4_fu_345_p2;
wire  signed [17:0] sext_ln74_4_fu_351_p1;
wire  signed [17:0] sext_ln74_3_fu_341_p1;
wire  signed [18:0] sext_ln74_5_fu_364_p1;
wire  signed [18:0] sext_ln74_2_fu_361_p1;
wire   [18:0] add_ln74_6_fu_367_p2;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
end

dot_product_mac_unit grp_mac_unit_fu_213(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .a(vec_a_0),
    .b(vec_b_0),
    .ap_return(grp_mac_unit_fu_213_ap_return)
);

dot_product_mac_unit grp_mac_unit_fu_221(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .a(vec_a_1),
    .b(vec_b_1),
    .ap_return(grp_mac_unit_fu_221_ap_return)
);

dot_product_mac_unit grp_mac_unit_fu_229(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .a(vec_a_2),
    .b(vec_b_2),
    .ap_return(grp_mac_unit_fu_229_ap_return)
);

dot_product_mac_unit grp_mac_unit_fu_237(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .a(vec_a_3),
    .b(vec_b_3),
    .ap_return(grp_mac_unit_fu_237_ap_return)
);

dot_product_mac_unit grp_mac_unit_fu_245(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .a(vec_a_4),
    .b(vec_b_4),
    .ap_return(grp_mac_unit_fu_245_ap_return)
);

dot_product_mac_unit grp_mac_unit_fu_253(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .a(vec_a_5),
    .b(vec_b_5),
    .ap_return(grp_mac_unit_fu_253_ap_return)
);

dot_product_mac_unit grp_mac_unit_fu_261(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .a(vec_a_6),
    .b(vec_b_6),
    .ap_return(grp_mac_unit_fu_261_ap_return)
);

dot_product_mac_unit grp_mac_unit_fu_269(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .a(vec_a_7),
    .b(vec_b_7),
    .ap_return(grp_mac_unit_fu_269_ap_return)
);

dot_product_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .vec_a_0(vec_a_0),
    .vec_a_1(vec_a_1),
    .vec_a_2(vec_a_2),
    .vec_a_3(vec_a_3),
    .vec_a_4(vec_a_4),
    .vec_a_5(vec_a_5),
    .vec_a_6(vec_a_6),
    .vec_a_7(vec_a_7),
    .vec_b_0(vec_b_0),
    .vec_b_1(vec_b_1),
    .vec_b_2(vec_b_2),
    .vec_b_3(vec_b_3),
    .vec_b_4(vec_b_4),
    .vec_b_5(vec_b_5),
    .vec_b_6(vec_b_6),
    .vec_b_7(vec_b_7),
    .result(result),
    .result_ap_vld(result_ap_vld),
    .busy(1'd0),
    .busy_ap_vld(busy_ap_vld),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln74_2_reg_458 <= add_ln74_2_fu_329_p2;
        add_ln74_5_reg_463 <= add_ln74_5_fu_355_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        busy_ap_vld = 1'b1;
    end else begin
        busy_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        result_ap_vld = 1'b1;
    end else begin
        result_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln74_1_fu_319_p2 = ($signed(sext_ln59_fu_285_p1) + $signed(sext_ln60_fu_289_p1));

assign add_ln74_2_fu_329_p2 = ($signed(sext_ln74_1_fu_325_p1) + $signed(sext_ln74_fu_315_p1));

assign add_ln74_3_fu_335_p2 = ($signed(sext_ln61_fu_293_p1) + $signed(sext_ln62_fu_297_p1));

assign add_ln74_4_fu_345_p2 = ($signed(sext_ln63_fu_301_p1) + $signed(sext_ln64_fu_305_p1));

assign add_ln74_5_fu_355_p2 = ($signed(sext_ln74_4_fu_351_p1) + $signed(sext_ln74_3_fu_341_p1));

assign add_ln74_6_fu_367_p2 = ($signed(sext_ln74_5_fu_364_p1) + $signed(sext_ln74_2_fu_361_p1));

assign add_ln74_fu_309_p2 = ($signed(sext_ln58_fu_281_p1) + $signed(sext_ln57_fu_277_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign result = $signed(add_ln74_6_fu_367_p2);

assign sext_ln57_fu_277_p1 = $signed(grp_mac_unit_fu_213_ap_return);

assign sext_ln58_fu_281_p1 = $signed(grp_mac_unit_fu_221_ap_return);

assign sext_ln59_fu_285_p1 = $signed(grp_mac_unit_fu_229_ap_return);

assign sext_ln60_fu_289_p1 = $signed(grp_mac_unit_fu_237_ap_return);

assign sext_ln61_fu_293_p1 = $signed(grp_mac_unit_fu_245_ap_return);

assign sext_ln62_fu_297_p1 = $signed(grp_mac_unit_fu_253_ap_return);

assign sext_ln63_fu_301_p1 = $signed(grp_mac_unit_fu_261_ap_return);

assign sext_ln64_fu_305_p1 = $signed(grp_mac_unit_fu_269_ap_return);

assign sext_ln74_1_fu_325_p1 = $signed(add_ln74_1_fu_319_p2);

assign sext_ln74_2_fu_361_p1 = $signed(add_ln74_2_reg_458);

assign sext_ln74_3_fu_341_p1 = $signed(add_ln74_3_fu_335_p2);

assign sext_ln74_4_fu_351_p1 = $signed(add_ln74_4_fu_345_p2);

assign sext_ln74_5_fu_364_p1 = $signed(add_ln74_5_reg_463);

assign sext_ln74_fu_315_p1 = $signed(add_ln74_fu_309_p2);

endmodule //dot_product
