// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module dot_product_mac_unit (
        ap_clk,
        ap_rst,
        a,
        b,
        ap_return
);


input   ap_clk;
input   ap_rst;
input  [7:0] a;
input  [7:0] b;
output  [15:0] ap_return;

wire    ap_block_pp0_stage0_11001;
wire    ap_block_pp0_stage0;
wire   [15:0] grp_fu_50_p2;
reg  signed [7:0] a_int_reg;
reg  signed [7:0] b_int_reg;
wire    ap_ce_reg;

dot_product_mul_8s_8s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_4_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b_int_reg),
    .din1(a_int_reg),
    .ce(1'b1),
    .dout(grp_fu_50_p2)
);

always @ (posedge ap_clk) begin
    a_int_reg <= a;
end

always @ (posedge ap_clk) begin
    b_int_reg <= b;
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_return = grp_fu_50_p2;

endmodule //dot_product_mac_unit
